# Generated by Django 2.2.24 on 2023-03-14 18:51

from django.db import migrations
from django.db.models import Case, When, F, Q


def fill_new_building_fields(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.update(
        new_building=Case(
            When(Q(construction_year__gte=2015), then=True),
            default=False,
            output_field=F('new_building'),
        )
    )


def rollback_new_building_fields(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.update(new_buiding=None)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building_fields, rollback_new_building_fields)
    ]
