# Generated by Django 2.2.24 on 2023-03-17 20:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_apartment', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
