# Generated by Django 2.2.24 on 2023-03-18 17:46

from django.db import migrations
import phonenumbers


def fill_owner_pure_phone_fields(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(phonenumber):
            flat.owner_pure_phone = phonenumbers.format_number(phonenumber, phonenumbers.PhoneNumberFormat.E164)
            flat.save()


def rollback_owner_pure_phone_fields(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = ''


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone_fields, rollback_owner_pure_phone_fields)
    ]
