# Generated by Django 2.2.24 on 2023-03-31 19:49

from django.db import migrations


def fill_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        flat_ids = owner.apartments.values_list('id', flat=True)
        new_flat_ids = [flat.id for flat in Flat.objects.filter(owners_phonenumber__contains=owner.phonenumber) if flat.id not in flat_ids]
        owner.apartments.set(new_flat_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20230331_2248'),
    ]

    operations = [
        migrations.RunPython(fill_owners)
    ]
